//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmrhao.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserId { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage = "This field is required.")]
        public string UserName { get; set; }
        [DisplayName("Full Name")]
        public string UserFullName { get; set; }
        [DisplayName("User Password")]
        [Required(ErrorMessage = "This field is required.")]
        public string UserPass { get; set; }
        public string UserTheme { get; set; }
        [DisplayName("User Role")]
        [Required(ErrorMessage = "This field is required.")]
        public string UserRole { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
